    create table exercises (
        id bigint generated by default as identity,
        description varchar(255),
        name varchar(50),
        number_of_approaches bigint not null check (number_of_approaches>=1),
        number_of_times bigint not null check (number_of_times>=1), primary key (id)
    );

    create table exercises_program_list (
        exercise_id bigint not null,
        program_list_id bigint not null
    );

    create table programs (
        id bigint generated by default as identity,
         user_id bigint, primary key (id)
    );

    create table programs_exercise_list (
        program_id bigint not null,
        exercise_list_id bigint not null
    );

    create table programs_sports_nutrition_list (
        program_id bigint not null,
        sports_nutrition_list_id bigint not null
    );

    create table roles (
        id bigint generated by default as identity,
        name varchar(50),
        user_id bigint, primary key (id)
    );

    create table shops (
        id bigint generated by default as identity,
        address varchar(30),
        city varchar(20),
        name varchar(50), primary key (id)
    );

    create table sportnutritions (
        id bigint generated by default as identity,
         description varchar(255),
         name varchar(50),
         sports_supplement varchar(255), primary key (id)
    );

    create table sportnutritions_list_program (
        sports_nutrition_id bigint not null,
        list_program_id bigint not null
    );

    create table sportnutritions_shop_list (
        sports_nutrition_list_id bigint not null,
         shop_list_id bigint not null
    );

    create table users (
        id bigint generated by default as identity,
        username varchar(50),
        password varchar(255),
        first_name varchar(50),
        last_name varchar(50),
        email varchar(255),
        age bigint not null check (age>=1),
        weight bigint not null check (weight>=1), primary key (id),
        growth bigint not null check (growth>=1),
        mission varchar(255),
        status varchar(255)
    );

    alter table exercises_program_list add constraint exercises_program_list_program_list_id_fk foreign key (program_list_id) references programs
    alter table exercises_program_list add constraint exercises_program_list_exercise_id_fk foreign key (exercise_id) references exercises
    alter table programs add constraint programs_user_id_k foreign key (user_id) references users
    alter table programs_exercise_list add constraint programs_exercise_list_exercise_list_id_fk foreign key (exercise_list_id) references exercises

    alter table programs_exercise_list add constraint FKnthqdw3idglu9eu0xv3ai2ab3 foreign key (program_id) references programs
    alter table programs_sports_nutrition_list add constraint FKkhw8hp9kaxjoncnr61b11jgki foreign key (sports_nutrition_list_id) references sportnutritions
    alter table programs_sports_nutrition_list add constraint FKegiqxc458d4g546jc856udcny foreign key (program_id) references programs
    alter table roles add constraint FK97mxvrajhkq19dmvboprimeg1 foreign key (user_id) references users
    alter table sportnutritions_list_program add constraint FK5xbc93hponarn4c45m498b2xm foreign key (list_program_id) references programs
    alter table sportnutritions_list_program add constraint FKgqu5yuk02c4subotu44iewfgr foreign key (sports_nutrition_id) references sportnutritions
    alter table sportnutritions_shop_list add constraint FKqvh4t7ppbjeviv1kgi91vsows foreign key (shop_list_id) references shops
    alter table sportnutritions_shop_list add constraint FKj441ergykjgc0evg5j0tm1nee foreign key (sports_nutrition_list_id) references sportnutritions